# Shows a "Sponsor" button at the top of the GitHub repo.
# Points directly to the one-time "Buy me a coffee" ($5) on Patreon.
custom: ["https://www.patreon.com/sksoumik/posts/buy-me-coffee-161839549"]
